name: teste
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  # muda de versao para a mais atual do seu flutter

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/bienal.png
    - images/Lollapalooza3.png
    - images/PosterCinema.jpg
    - images/jazz1.jpg
    - images/expoarte1.jpg
    # adiciona as imagens aqui nesse padrao... e coloca elas na pastinha images
